name: flutter_test
description: Learn Flutter.
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: 1.1.2  

flutter:
  assets:
    - lib/main.dart



